science_popularity_scientists_put:
    pattern:  /scientists/{id}
    defaults: { _controller: SciencePopularityBundle:Default:putScientists }
    methods: [PUT]
    requirements:
        _format: json

science_popularity_scientists_get:
    pattern:  /scientists/{id}
    defaults: { _controller: SciencePopularityBundle:Default:getScientists, id: null }
    methods: [GET]

science_popularity_homepage:
    pattern:  /
    defaults: { _controller: SciencePopularityBundle:Default:index }
    methods: [GET]