science_popularity_scientists_get:
    pattern:  /scientists/{id}
    defaults: { _controller: SciencePopularityBundle:Default:getScientists, id: null }
    requirements:
        _method: GET

science_popularity_scientists_put:
    pattern:  /scientists/{:id}
    defaults: { _controller: SciencePopularityBundle:Default:putScientists }
    requirements:
        _method: PUT

science_popularity_homepage:
    pattern:  /foo
    defaults: { _controller: SciencePopularityBundle:Default:index }