parameters:
    science_popularity.scientists.class: Science\PopularityBundle\Service\ScientistsService
    science_popularity.storage.class: Science\PopularityBundle\Util\FixtureStorage
    science_popularity.fixtures: '../src/Science/PopularityBundle/Resources/fixtures/'
    science_popularity.scientist.factory.class: Science\PopularityBundle\Factory\ScientistFactory

services:
    science_popularity.scientists:
        class: %science_popularity.scientists.class%
        arguments: [@science_popularity.storage]

    science_popularity.storage:
        class: %science_popularity.storage.class%
        arguments: [%science_popularity.fixtures%]

    science_popularity.scientist.factory:
        class: %science_popularity.scientist.factory.class%